### ISSUE TITLE
translate/TranslationAndCleaning

### ISSUE THREAD

**Issue by sipheleledanisa** [michelleg06/Educational_Outcomes_Ecuador#5]

**Comment by AFbenHassine** [comment]
I decided on using feather (install as ``feather-format``) to save and load the large dataset.

**Comment by AFbenHassine** [comment]
Should be completed with commit https://github.com/michelleg06/Educational_Outcomes_Ecuador/commit/d836bdbc05f5c82cccdd88ed9bfb01873eabc5c7.
